// <auto-generated />
using System;
using DataTransformation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataTransformation.Migrations
{
    [DbContext(typeof(DataTransformationContext))]
    [Migration("20210111091454_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataTransformation.Models.VendorMapping", b =>
                {
                    b.Property<int>("MappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CDM_MAPPING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMMENTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("DB_FIELD_NM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDDS_TRSFM_LOGIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDDS_XML")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_TRSFM_LOGIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_XML")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EDIT_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("RO_TRSFM_LOGIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_XML")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UI_FIELD_NM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MappingID");

                    b.ToTable("VendorMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
